### ISSUE TITLE
Specify an offset of "time coordinate"

### ISSUE THREAD

**Issue by KronosTheLate** [pta2002/typst-timeliney#5]
Currently, the time coordinate is given as (0, 1) for an entry starting at the start and spanning one time-unit.

It would be great if a keyword argument `offset` could be passed to `timeliney.timeline`. It would have the effect of being added to all temporal coordinates before the actual evaluation.

The intended use case is if you have a Gantt diagram that starts at e.g.  week 3, then you could specify an offset of `-3`. This would make it so that `(3, 4)`, which naturally reads like "from 3 to 4" is automatically converted to `(0, 1)`, mapping it to the natural reading (for this specific diagram, which starts at 3).

Without this functionality, when working with my diagram going from week 6 to week 22, I found myself aligning the time-coordinate by trial and error instead of just setting the right value from the start.

**Comment by pta2002** [comment]
Hey, thanks for all the requests! Unfortunately I can't work on them right at the moment because I just started a new job and have been busy with that, but either this weekend or on the next one I can work on these. None of them should be particularly difficult.

**Comment by KronosTheLate** [comment]
Cool! I am in the middle of an exam period and can very much relate. Take your time, and thank you for (a) concidering my proposals, and (b) this package - it came in very handy when writing the project description for my masters thesis today ^_^

**Comment by KronosTheLate** [comment]
I could not find a comment to react to, so here is a heart: <3

Once a new version is tagged, it would be cool to have an example in the documentation. Sidenote on that - have you concidered making a github-hosted documentation page? It would make the package somewhat more accessable than the current PDF-in-repo solution ^_^

**Comment by pta2002** [comment]
Yeah I've looked a bit into it and it would be hard-ish at the moment because Typst's HTML export isn't a thing yet, so I'd need to do something like markdown with Typst included... if something like that exists already then I can use it, otherwise I guess that'd be a brand new project

**Comment by KronosTheLate** [comment]
I was looking to update the package, and use this feature. However it seems like a new version has not been tagged. Are there other things you would like to get into 0.2.0 (I think new features can not be added in patch-releases if we care about SemVer), or would you be okay with tagging a new release soon?

**Comment by pta2002** [comment]
Well I was planning to add the other issues but since this is going to take
a bit I guess I can tag out a new release today. Once I get home from work
I'll take care of it.
